import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
// import { AppSidebar } from "@/components/layouts/default-layout";
import { AppSidebar } from "@/components/layouts/default-layout";
import { Toaster } from "sonner";
import { cookies } from "next/headers";
import { authStore } from "../store/auth.store";
import HydrateUser from "@/components/HydrateUser";
import { decrypt } from "../libs/session";
import QueryProvider from "@/components/provider";
import { DialogAlertInfo } from "@/components/layouts/page-layout";
// import AppSidebar from "@/components/layouts/app-sider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = (await cookies()).get("session")?.value;
  const session = await decrypt(cookie);

  return (
    <html lang="en">
      <body className={`  antialiased`}>
        <HydrateUser user={session} />
        <QueryProvider>
          <SidebarProvider>
            <AppSidebar />
            <main className="w-full max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
              {/* <SidebarTrigger /> */}
              {children}
            </main>
          </SidebarProvider>
        </QueryProvider>
        <Toaster position="top-center" />
        {/* <DialogAlertInfo /> */}
      </body>
    </html>
  );
}
