import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
// import { AppSidebar } from "@/components/layouts/default-layout";
import { AppSidebar } from "@/components/layouts/default-layout";
import { Toaster } from "sonner";
// import AppSidebar from "@/components/layouts/app-sider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`  antialiased`}>
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
            {/* <SidebarTrigger /> */}
            {children}
          </main>
        </SidebarProvider>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
