import type { Metadata } from "next";
import "./globals.css";
import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarGroup,
  SidebarGroupContent,
  SidebarHeader,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarTrigger,
  SidebarProvider,
} from "@/components/ui/sidebar";
// import { AppSidebar } from "@/components/layouts/default-layout";
import { route } from "@/lib/route";
import { Home, Inbox, Calendar, Settings } from "lucide-react";
import { Logo } from "../(auth)/login/page";
import { Button } from "@/components/ui/button";
import {
  AppSidebar,
  DefaultLayoutContainer,
} from "@/components/layouts/default-layout";
// import AppSidebar from "@/components/layouts/app-sider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`  antialiased`}>
        <SidebarProvider>
          <AppSidebar />
          <main>
            <SidebarTrigger />
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
